import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Go up one level to project root
const rootDir = dirname(__dirname)
const pkgPath = join(rootDir, 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))

// Parse current version (e.g., "1.2.0")
const [major, minor, patch] = pkg.version.split('.').map(Number)

// Increment patch version (1.2.0 → 1.2.1)
const newVersion = `${major}.${minor}.${patch + 1}`

// Generate new build timestamp
const now = new Date()
const buildTimestamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`

pkg.version = newVersion
pkg.build = buildTimestamp

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

// Write version info to a TypeScript file that can be imported
const versionTs = `// Auto-generated by scripts/patch.js - DO NOT EDIT
export const APP_VERSION = '${newVersion}'
export const APP_BUILD = '${buildTimestamp}'
`

writeFileSync(join(rootDir, 'src', 'version.ts'), versionTs)

console.log(`✅ Version bumped: ${pkg.version} → ${newVersion}`)
console.log(`✅ Build timestamp: ${buildTimestamp}`)