import { readFileSync, writeFileSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Go up one level to project root
const rootDir = dirname(__dirname)
const pkgPath = join(rootDir, 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))

// Generate new build timestamp
const now = new Date()
const buildTimestamp = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`

// Only bump the patch version if the build timestamp has changed
// This prevents double-bumping when deploy.sh calls npm run build
// after we've already built manually
const currentBuild = pkg.build || ''
let newVersion = pkg.version

if (currentBuild !== buildTimestamp) {
  // Build timestamp changed → this is a new build, bump the version
  const [major, minor, patch] = pkg.version.split('.').map(Number)
  newVersion = `${major}.${minor}.${patch + 1}`
  console.log(`✅ Version bumped: ${pkg.version} → ${newVersion}`)
} else {
  // Same build timestamp → version was already bumped for this build
  console.log(`✅ Version already bumped for this build: ${pkg.version} → ${newVersion}`)
}

pkg.version = newVersion
pkg.build = buildTimestamp

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

// Write version info to a TypeScript file that can be imported
const versionTs = `// Auto-generated by scripts/patch.js - DO NOT EDIT
export const APP_VERSION = '${newVersion}'
export const APP_BUILD = '${buildTimestamp}'
`

writeFileSync(join(rootDir, 'src', 'version.ts'), versionTs)

console.log(`✅ Build timestamp: ${buildTimestamp}`)